blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import HttpRequest, HttpResponse, Http404


def blog(request):
    print('cliente acessou a página de blog')

    context = {
        'text': 'Página de Blog!',
        'title': 'Blog - ',
        'posts': posts
    }

    return render(request, 'blog/index.html', context)


def post(request: HttpRequest, post_id: int) -> HttpResponse:
    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post inexistente.')

    context = {
        # 'text': 'Página de Post!',
        'title': found_post['title'] + ' - ',
        'post': found_post
    }

    return render(request, 'blog/post.html', context)


def exemplo(request):
    print('cliente acessou a página de exemplo')

    context = {
        'text': 'EXEMPLO',
        'title': 'EXEMPLO - '
    }

    return render(request, 'blog/exemplo.html', context)

home/views.py
from django.shortcuts import render

def home(request):
    print('cliente acessou a página principal')
    context = {
        'text': 'Página de Home!',
        'title': 'Home - '
    }

    return render(
        request,
        'home/index.html',
        context
    )

blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block tituloh1 %} {{ text }} {% endblock tituloh1 %}

blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block tituloh1 %} {{ text }} {% endblock tituloh1 %}

{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block tituloh1 %} {{ text }} {% endblock tituloh1 %}

{% block posts %}
    <article class="post single-post">
        <header>
            <a href="{% url 'blog:post' post.id %}">
                <h1 class="post__title">{{post.title}}</h1>
            </a>
        </header>
        <div class="post__body">
            {{post.body}}
        </div>
    </article>
{% endblock posts %}

home/templates/home/index.html
{% extends 'global/base.html' %}

{% block tituloh1 %} {{ text }} {% endblock tituloh1 %}

{% block home %}
    
{% endblock home %}